version: '3'

services:
  telegraf:
    image: telegraf
    container_name: telegraf-docker
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - INFLUXDB_DB
      - INFLUXDB_URL
    networks:
      - fluxana_influxdb

networks:
  fluxana_influxdb:
    external: true
