version: '3'

services:
  speedtest:
    build: ./docker
    container_name: speedtest
    restart: always
    networks:
      - fluxana_influxdb
    environment:
      - INFLUXDB_DB
      - INFLUXDB_URL
      - SPEEDTEST_HOST
      - SPEEDTEST_INTERVAL

networks:
  fluxana_influxdb:
    external: true
