version: '3' 

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - "${DATA_DIR}/nginx/conf.d:/etc/nginx/conf.d:rw"
      - "${DATA_DIR}/nginx/vhost.d:/etc/nginx/vhost.d:rw"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html:rw"
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs:ro"
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - nextcloud_network
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs:rw"
      - "${DATA_DIR}/nginx/vhost.d:/etc/nginx/vhost.d:rw"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html:rw"
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - "${DATA_DIR}/db:/var/lib/mysql"
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    restart: unless-stopped
  
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - "${DATA_DIR}/nextcloud:/var/www/html"
      - "${DATA_DIR}/db:/var/lib/mysql"
      - "${DATA_DIR}/app/config:/var/www/html/config"
      - "${DATA_DIR}/app/custom_apps:/var/www/html/custom_apps"
      - "${DATA_DIR}/app/data:/var/www/html/data"
      - "${DATA_DIR}/app/themes:/var/www/html/themes"
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_HOST
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    restart: unless-stopped

  backups:
    image: christophetd/duplicacy-autobackup:v1.0
    container_name: backups
    restart: always
    environment:
      - BACKUP_NAME
      - BACKUP_LOCATION
      - BACKUP_SCHEDULE
      - BACKUP_IMMEDIATELY
      - BACKUP_ENCRYPTION_KEY
    volumes:
      - "${DATA_DIR}:/data"
      - /forest/data/nextcloud-data:/backups

networks:
  nextcloud_network:
