version: '3'

services:
  modem-stats:
    build: ./
    container_name: modem-stats
    restart: always
    networks:
      - fluxana_influxdb
    environment:
      - ROUTER_URL
      - ROUTER_USER
      - ROUTER_PASS
      - INFLUXDB_URL
      - DATABASE

networks:
  fluxana_influxdb:
    external: true
