# to run: docker-compose run
#
# Create a .env file in the same folder as this file and change the variables.
# MOUNT_POINT=/tmp/
# MEDIA_MOUNT_POINT=/media/
# VPN_PROVIDER=changeme
# VPN_CONFIG=changeme
# VPN_USERNAME=changeme
# VPN_PASSWORD=changeme
# WEBPROXY_ENABLED=false
# LOCAL_NETWORK=192.168.0.0/16
#
#

version: "3"

services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "9092:9091"
    networks:
      - sportnet
    environment:
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings
      - TRANSMISSION_SPEED_LIMIT_UP
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED
    volumes:
      - ${MOUNT_POINT}/transmission:/data
      - /etc/localtime:/etc/localtime:ro
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    networks:
      - sportnet
    environment:
      - PGID=65536
      - PUID=1000
      - TZ=America/Denver
    volumes:
      - ${MOUNT_POINT}/radarr-config:/config
      - ${MOUNT_POINT}/transmission/completed:/data/completed
      - ${MEDIA_MOUNT_POINT}/Movies:/movies
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    networks:
      - sportnet
    environment:
      - PGID=65536
      - PUID=1000
      - TZ=America/Denver
    volumes:
      - ${MOUNT_POINT}/sonarr/config:/config
      - ${MOUNT_POINT}/transmission/completed:/data/completed
      - ${MEDIA_MOUNT_POINT}/TV:/tv


networks:
  sportnet:
    driver: bridge
