version: '3'

services:
  mc-spiderham:
    container_name: 'mc-spiderham'
    image: itzg/minecraft-server
    restart: always
    stdin_open: true
    tty: true
    environment:
      - EULA=TRUE
      - MEMORY=2G
    ports:
      - 25565:25565
    volumes:
      - ~/data/minecraft-spiderham:/data

# docker attach mc-spiderham
# to attach and do minecraft commands
